In [1]:
import pandas as pd
from sklearn import preprocessing
import numpy as np
from keras.models import load_model

Using TensorFlow backend.

In [29]:
df = pd.read_csv('./data/dataset_wx_web.csv')
df

,date,oneDayBefore,twoDayBefore,threeDayBefore,oneMonthBefore,oneYearBefore,dollorRate,price
0,2015-01-01,2.36,2.33,2.350000,2.450000,2.84,611.951534,2.49
1,2015-01-02,2.49,2.36,2.330000,2.420000,2.84,611.900024,2.52
2,2015-01-03,2.52,2.49,2.360000,2.360000,2.84,611.900024,2.53
3,2015-01-04,2.53,2.52,2.490000,2.290000,2.88,611.900024,2.25
4,2015-01-05,2.25,2.53,2.520000,2.360000,2.92,611.900024,2.31
5,2015-01-06,2.31,2.25,2.530000,2.410000,2.98,612.452795,2.28
6,2015-01-07,2.28,2.31,2.250000,2.380000,2.60,612.550739,2.24
7,2015-01-08,2.24,2.28,2.310000,2.450000,2.82,612.666668,2.28
8,2015-01-09,2.28,2.24,2.280000,2.300000,2.74,612.978421,2.28
9,2015-01-10,2.28,2.28,2.240000,2.240000,2.83,612.965682,2.33
10,2015-01-11,2.33,2.28,2.280000,2.320000,2.81,612.960022,2.52
11,2015-01-12,2.52,2.33,2.280000,2.420000,2.95,612.960022,2.58
12,2015-01-13,2.58,2.52,2.330000,2.270000,3.12,612.404684,2.39
13,2015-01-14,2.39,2.58,2.520000,2.340000,3.24,611.999128,2.42
14,2015-01-15,2.42,2.39,2.580000,2.450000,3.17,612.040556,2.34
15,2015-01-16,2.34,2.42,2.390000,2.360000,2.86,611.938856,2.44
16,2015-01-17,2.44,2.34,2.420000,2.310000,2.88,611.883806,2.45
17,2015-01-18,2.45,2.44,2.340000,2.350000,2.93,611.880005,2.46
18,2015-01-19,2.46,2.45,2.440000,2.380000,2.92,611.880005,2.52
19,2015-01-20,2.52,2.46,2.450000,2.260000,2.96,612.260226,2.38
20,2015-01-21,2.38,2.52,2.460000,2.300000,2.89,612.265224,2.44
21,2015-01-22,2.44,2.38,2.520000,2.450000,2.87,612.603300,2.52
22,2015-01-23,2.52,2.44,2.380000,2.270000,2.96,612.500666,2.58
23,2015-01-24,2.58,2.52,2.440000,2.280000,3.04,613.245935,2.45
24,2015-01-25,2.45,2.58,2.520000,2.340000,3.02,613.419983,2.53
25,2015-01-26,2.53,2.45,2.580000,2.340000,3.12,613.419983,2.48
26,2015-01-27,2.48,2.53,2.450000,2.450000,3.15,613.782421,2.47
27,2015-01-28,2.47,2.48,2.530000,2.350000,3.07,613.663792,2.50
28,2015-01-29,2.50,2.47,2.480000,2.350000,3.57,612.909463,2.44
29,2015-01-30,2.44,2.50,2.470000,2.330000,3.57,613.280699,2.49
...,...,...,...,...,...,...,...,...
1462,2018-12-02,2.13,2.11,2.130000,2.090000,2.24,693.570007,2.19
1463,2018-12-03,2.19,2.13,2.110000,2.110000,2.18,693.570007,2.13
1464,2018-12-04,2.13,2.19,2.130000,2.120000,2.14,694.250200,2.18
1465,2018-12-05,2.18,2.13,2.190000,2.080000,2.20,689.708036,2.14
1466,2018-12-06,2.14,2.18,2.130000,2.100000,2.14,685.347574,2.18
1467,2018-12-07,2.18,2.14,2.180000,2.070000,2.15,685.871363,2.20
1468,2018-12-08,2.20,2.18,2.140000,2.100000,2.11,686.607693,2.30
1469,2018-12-09,2.30,2.20,2.180000,2.050000,2.13,686.640015,2.33
1470,2018-12-10,2.33,2.30,2.200000,2.120000,2.12,686.640015,2.22
1471,2018-12-11,2.22,2.33,2.300000,1.950000,2.10,686.911404,2.22
1472,2018-12-12,2.22,2.22,2.330000,2.010000,2.04,689.756208,2.13
1473,2018-12-13,2.13,2.22,2.220000,2.070000,2.11,690.573417,2.18
1474,2018-12-14,2.18,2.13,2.220000,2.100000,2.10,687.939739,2.20
1475,2018-12-15,2.20,2.18,2.130000,2.120000,2.13,687.525763,2.16
1476,2018-12-16,2.16,2.20,2.180000,2.160000,2.16,687.500000,2.21
1477,2018-12-17,2.21,2.16,2.200000,2.190000,2.07,687.500000,2.20
1478,2018-12-18,2.20,2.21,2.160000,2.240000,2.06,688.901628,2.16
1479,2018-12-19,2.16,2.20,2.210000,2.140000,2.03,688.619122,2.16
1480,2018-12-20,2.16,2.16,2.200000,2.170000,2.05,688.680001,2.13
1481,2018-12-21,2.13,2.16,2.160000,2.170000,1.99,689.269558,2.17
1482,2018-12-22,2.17,2.13,2.160000,2.150000,1.96,688.354253,2.14
1483,2018-12-23,2.14,2.17,2.130000,2.140000,1.94,688.250000,2.11
1484,2018-12-24,2.11,2.14,2.170000,2.160000,2.07,688.250000,2.11
1485,2018-12-25,2.11,2.11,2.140000,2.170000,2.02,689.861642,2.16
1486,2018-12-26,2.16,2.11,2.110000,2.110000,1.98,689.293573,2.19
1487,2018-12-27,2.19,2.16,2.110000,2.140000,1.95,688.505978,2.20
1488,2018-12-28,2.20,2.19,2.160000,2.170000,1.94,688.878754,2.17
1489,2018-12-29,2.17,2.20,2.190000,2.130000,1.94,686.579278,2.17
1490,2018-12-30,2.17,2.17,2.200000,2.110000,1.99,686.320007,2.27
1491,2018-12-31,2.27,2.17,2.265104,2.268867,2.06,686.320007,2.18

In [31]:
df =df.drop_duplicates(subset='date', keep='first', inplace=False)
df.set_index('date')
sd.to_csv('./data/dataset_wx_web.csv')

,oneDayBefore,twoDayBefore,threeDayBefore,oneMonthBefore,oneYearBefore,dollorRate,price
date,,,,,,,
2015-01-01,2.36,2.33,2.350000,2.450000,2.84,611.951534,2.49
2015-01-02,2.49,2.36,2.330000,2.420000,2.84,611.900024,2.52
2015-01-03,2.52,2.49,2.360000,2.360000,2.84,611.900024,2.53
2015-01-04,2.53,2.52,2.490000,2.290000,2.88,611.900024,2.25
2015-01-05,2.25,2.53,2.520000,2.360000,2.92,611.900024,2.31
2015-01-06,2.31,2.25,2.530000,2.410000,2.98,612.452795,2.28
2015-01-07,2.28,2.31,2.250000,2.380000,2.60,612.550739,2.24
2015-01-08,2.24,2.28,2.310000,2.450000,2.82,612.666668,2.28
2015-01-09,2.28,2.24,2.280000,2.300000,2.74,612.978421,2.28
2015-01-10,2.28,2.28,2.240000,2.240000,2.83,612.965682,2.33
2015-01-11,2.33,2.28,2.280000,2.320000,2.81,612.960022,2.52
2015-01-12,2.52,2.33,2.280000,2.420000,2.95,612.960022,2.58
2015-01-13,2.58,2.52,2.330000,2.270000,3.12,612.404684,2.39
2015-01-14,2.39,2.58,2.520000,2.340000,3.24,611.999128,2.42
2015-01-15,2.42,2.39,2.580000,2.450000,3.17,612.040556,2.34
2015-01-16,2.34,2.42,2.390000,2.360000,2.86,611.938856,2.44
2015-01-17,2.44,2.34,2.420000,2.310000,2.88,611.883806,2.45
2015-01-18,2.45,2.44,2.340000,2.350000,2.93,611.880005,2.46
2015-01-19,2.46,2.45,2.440000,2.380000,2.92,611.880005,2.52
2015-01-20,2.52,2.46,2.450000,2.260000,2.96,612.260226,2.38
2015-01-21,2.38,2.52,2.460000,2.300000,2.89,612.265224,2.44
2015-01-22,2.44,2.38,2.520000,2.450000,2.87,612.603300,2.52
2015-01-23,2.52,2.44,2.380000,2.270000,2.96,612.500666,2.58
2015-01-24,2.58,2.52,2.440000,2.280000,3.04,613.245935,2.45
2015-01-25,2.45,2.58,2.520000,2.340000,3.02,613.419983,2.53
2015-01-26,2.53,2.45,2.580000,2.340000,3.12,613.419983,2.48
2015-01-27,2.48,2.53,2.450000,2.450000,3.15,613.782421,2.47
2015-01-28,2.47,2.48,2.530000,2.350000,3.07,613.663792,2.50
2015-01-29,2.50,2.47,2.480000,2.350000,3.57,612.909463,2.44
2015-01-30,2.44,2.50,2.470000,2.330000,3.57,613.280699,2.49
...,...,...,...,...,...,...,...
2018-12-02,2.13,2.11,2.130000,2.090000,2.24,693.570007,2.19
2018-12-03,2.19,2.13,2.110000,2.110000,2.18,693.570007,2.13
2018-12-04,2.13,2.19,2.130000,2.120000,2.14,694.250200,2.18
2018-12-05,2.18,2.13,2.190000,2.080000,2.20,689.708036,2.14
2018-12-06,2.14,2.18,2.130000,2.100000,2.14,685.347574,2.18
2018-12-07,2.18,2.14,2.180000,2.070000,2.15,685.871363,2.20
2018-12-08,2.20,2.18,2.140000,2.100000,2.11,686.607693,2.30
2018-12-09,2.30,2.20,2.180000,2.050000,2.13,686.640015,2.33
2018-12-10,2.33,2.30,2.200000,2.120000,2.12,686.640015,2.22
2018-12-11,2.22,2.33,2.300000,1.950000,2.10,686.911404,2.22
2018-12-12,2.22,2.22,2.330000,2.010000,2.04,689.756208,2.13
2018-12-13,2.13,2.22,2.220000,2.070000,2.11,690.573417,2.18
2018-12-14,2.18,2.13,2.220000,2.100000,2.10,687.939739,2.20
2018-12-15,2.20,2.18,2.130000,2.120000,2.13,687.525763,2.16
2018-12-16,2.16,2.20,2.180000,2.160000,2.16,687.500000,2.21
2018-12-17,2.21,2.16,2.200000,2.190000,2.07,687.500000,2.20
2018-12-18,2.20,2.21,2.160000,2.240000,2.06,688.901628,2.16
2018-12-19,2.16,2.20,2.210000,2.140000,2.03,688.619122,2.16
2018-12-20,2.16,2.16,2.200000,2.170000,2.05,688.680001,2.13
2018-12-21,2.13,2.16,2.160000,2.170000,1.99,689.269558,2.17
2018-12-22,2.17,2.13,2.160000,2.150000,1.96,688.354253,2.14
2018-12-23,2.14,2.17,2.130000,2.140000,1.94,688.250000,2.11
2018-12-24,2.11,2.14,2.170000,2.160000,2.07,688.250000,2.11
2018-12-25,2.11,2.11,2.140000,2.170000,2.02,689.861642,2.16
2018-12-26,2.16,2.11,2.110000,2.110000,1.98,689.293573,2.19
2018-12-27,2.19,2.16,2.110000,2.140000,1.95,688.505978,2.20
2018-12-28,2.20,2.19,2.160000,2.170000,1.94,688.878754,2.17
2018-12-29,2.17,2.20,2.190000,2.130000,1.94,686.579278,2.17
2018-12-30,2.17,2.17,2.200000,2.110000,1.99,686.320007,2.27
2018-12-31,2.27,2.17,2.265104,2.268867,2.06,686.320007,2.18

In [3]:
# 标准化
X_data = df.iloc[:, 0:-1]
Y_data = df['price'].values.reshape(-1, 1)
scaler_X = preprocessing.StandardScaler(copy=True, with_mean=True, with_std=True).fit(X_data)
scaler_Y = preprocessing.StandardScaler(copy=True, with_mean=True, with_std=True).fit(Y_data)

In [14]:
startDate = "2018-12-3"
endDate = "2018-12-31"
df = df.loc[startDate:endDate]
df

,oneDayBefore,twoDayBefore,threeDayBefore,oneMonthBefore,oneYearBefore,dollorRate,price
date,,,,,,,
2018-12-30,2.17,2.17,2.200000,2.110000,1.99,686.320007,2.27
2018-12-31,2.27,2.17,2.265104,2.268867,2.06,686.320007,2.18

In [13]:
datelist = pd.date_range(startDate,endDate)
datelist = [x.strftime('%Y-%m-%d') for x in datelist]
datelist

['2018-11-30',
 '2018-12-01',
 '2018-12-02',
 '2018-12-03',
 '2018-12-04',
 '2018-12-05',
 '2018-12-06',
 '2018-12-07',
 '2018-12-08',
 '2018-12-09',
 '2018-12-10',
 '2018-12-11',
 '2018-12-12',
 '2018-12-13',
 '2018-12-14',
 '2018-12-15',
 '2018-12-16',
 '2018-12-17',
 '2018-12-18',
 '2018-12-19',
 '2018-12-20',
 '2018-12-21',
 '2018-12-22',
 '2018-12-23',
 '2018-12-24',
 '2018-12-25',
 '2018-12-26',
 '2018-12-27',
 '2018-12-28',
 '2018-12-29',
 '2018-12-30',
 '2018-12-31']

In [5]:
X = scaler_X.transform(df.iloc[:,0:-1])
X

array([[-3.90921118e-01, -5.24281955e-01, -6.18903371e-01,
        -2.64339615e-01,  4.97960288e-01, -9.14847769e-02],
       [-4.09987324e-01, -3.90825114e-01, -5.23717915e-01,
        -5.49489353e-02,  4.12178421e-01, -9.14847769e-02],
       [-4.67185942e-01, -4.09890377e-01, -3.90458276e-01,
        -1.69162034e-01,  1.37676447e-01, -1.77108837e-01],
       ...,
       [-1.81192852e-01, -1.23911431e-01, -1.42976089e-01,
        -2.64339615e-01, -7.37298597e-01,  1.17399293e+00],
       [-1.81192852e-01, -1.81107221e-01, -1.23938998e-01,
        -3.02410648e-01, -6.51516730e-01,  1.16409824e+00],
       [ 9.46920822e-03, -1.81107221e-01,  0.00000000e+00,
        -2.53604023e-15, -5.31422116e-01,  1.16409824e+00]])

In [6]:
Y = scaler_Y.transform(df['price'].values.reshape(-1, 1))
Y

array([[-0.40904066],
       [-0.46623735],
       [-0.5424996 ],
       [-0.42810622],
       [-0.44717179],
       [-0.37090954],
       [-0.42810622],
       [-0.40904066],
       [-0.63782742],
       [-0.59969629],
       [-0.73315523],
       [-0.56156516],
       [-0.63782742],
       [-0.5424996 ],
       [-0.63782742],
       [-0.61876185],
       [-0.65689298],
       [-0.61876185],
       [-0.61876185],
       [-0.42810622],
       [-0.46623735],
       [-0.6950241 ],
       [-0.59969629],
       [-0.48530291],
       [-0.33277841],
       [-0.08492609],
       [-0.08492609],
       [-0.04679497],
       [-0.37090954],
       [-0.56156516],
       [-0.48530291],
       [-0.61876185],
       [-0.63782742],
       [-0.61876185],
       [-0.3899751 ],
       [-0.52343404],
       [-0.44717179],
       [-0.50436848],
       [-0.42810622],
       [-0.42810622],
       [-0.33277841],
       [-0.0277294 ],
       [-0.25651616],
       [ 0.06759841],
       [ 0.18199179],
       [ 0.4298441 ],
       [-0.37090954],
       [-0.37090954],
       [-0.37090954],
       [-0.37090954],
       [-0.37090954],
       [-0.37090954],
       [-0.37090954],
       [-0.27558172],
       [-0.12305722],
       [-0.29464728],
       [-0.21838503],
       [-0.14212278],
       [-0.14212278],
       [-0.14212278],
       [-0.14212278],
       [-0.14212278],
       [-0.10399166],
       [-0.18025391],
       [-0.10399166],
       [ 0.01040172],
       [-0.31371285],
       [-0.29464728],
       [-0.2374506 ],
       [-0.31371285],
       [-0.27558172],
       [-0.25651616],
       [-0.25651616],
       [-0.31371285],
       [-0.40904066],
       [-0.48530291],
       [-0.2374506 ],
       [-0.31371285],
       [-0.48530291],
       [-0.33277841],
       [-0.19931947],
       [-0.37090954],
       [-0.48530291],
       [-0.59969629],
       [-0.5424996 ],
       [-0.61876185],
       [-1.00007311],
       [-0.50436848],
       [-0.75222079],
       [-0.75222079],
       [-0.79035192],
       [-0.58063073],
       [-0.50436848],
       [-0.71408967],
       [-0.52343404],
       [-0.52343404],
       [-0.56156516],
       [-0.3899751 ],
       [-0.27558172],
       [-0.67595854],
       [-0.79035192],
       [-0.27558172],
       [-0.40904066],
       [-0.52343404],
       [-0.52343404],
       [-0.48530291],
       [-0.5424996 ],
       [-0.2374506 ],
       [-0.18025391],
       [-0.18025391],
       [-0.25651616],
       [-0.14212278],
       [-0.16118834],
       [ 0.37264742],
       [ 0.10572954],
       [ 0.16292622],
       [-0.0277294 ],
       [ 0.14386066],
       [ 0.16292622],
       [ 0.37264742],
       [ 0.44890967],
       [ 0.29638516],
       [ 0.2773196 ],
       [ 0.2773196 ],
       [ 0.29638516],
       [ 0.29638516],
       [ 0.20105735],
       [ 0.25825404],
       [ 0.33451629],
       [ 0.46797523],
       [ 0.33451629],
       [ 0.20105735],
       [ 0.20105735],
       [-0.0277294 ],
       [ 0.1247951 ],
       [ 0.06759841],
       [ 0.31545073],
       [ 0.20105735],
       [ 0.2773196 ],
       [ 0.56330304],
       [ 0.56330304],
       [ 0.33451629],
       [ 0.25825404],
       [ 0.1247951 ],
       [ 0.10572954],
       [-0.06586053],
       [-0.16118834],
       [-0.12305722],
       [-0.0277294 ],
       [ 0.01040172],
       [ 0.02946728],
       [-0.00866384],
       [ 0.01040172],
       [-0.0277294 ],
       [-0.0277294 ],
       [-0.0277294 ],
       [-0.12305722],
       [-0.08492609],
       [-0.08492609],
       [-0.06586053],
       [-0.19931947],
       [-0.18025391],
       [-0.21838503],
       [-0.25651616],
       [-0.2374506 ],
       [-0.35184397],
       [-0.21838503],
       [-0.19931947],
       [-0.2374506 ],
       [-0.46623735],
       [-0.31371285],
       [-0.35184397],
       [-0.19931947],
       [-0.27558172],
       [-0.31371285],
       [-0.3899751 ],
       [-0.35184397],
       [-0.65689298],
       [-0.5424996 ],
       [-0.46623735],
       [-0.59969629],
       [-0.42810622],
       [-0.40904066],
       [-0.50436848],
       [-0.44717179],
       [-0.44717179],
       [-0.56156516],
       [-0.56156516],
       [-0.73315523],
       [-0.63782742],
       [-0.65689298],
       [-0.6950241 ],
       [-0.79035192],
       [-0.92381086],
       [-0.98100755],
       [-0.98100755],
       [-1.00007311],
       [-0.88567973],
       [-1.00007311],
       [-1.00007311],
       [-0.94287642],
       [-0.92381086],
       [-0.88567973],
       [-0.96194198],
       [-1.01913867],
       [-1.03820424],
       [-0.92381086],
       [-0.9047453 ],
       [-0.92381086],
       [-0.84754861],
       [-0.80941748],
       [-0.79035192],
       [-0.6950241 ],
       [-0.58063073],
       [-0.61876185],
       [-0.52343404],
       [-0.61876185],
       [-0.59969629],
       [-0.48530291],
       [-0.50436848],
       [-0.50436848],
       [-0.21838503],
       [-0.25651616],
       [-0.29464728],
       [-0.37090954],
       [-0.37090954],
       [-0.42810622],
       [-0.42810622],
       [-0.3899751 ],
       [-0.27558172],
       [-0.14212278],
       [-0.04679497],
       [ 0.06759841],
       [-0.0277294 ],
       [-0.35184397],
       [-0.18025391],
       [-0.16118834],
       [-0.29464728],
       [-0.29464728],
       [-0.31371285],
       [-0.44717179],
       [-0.50436848],
       [-0.35184397],
       [-0.46623735],
       [-0.46623735],
       [-0.3899751 ],
       [-0.40904066],
       [-0.3899751 ],
       [-0.44717179],
       [-0.5424996 ],
       [-0.42810622],
       [-0.56156516],
       [-0.58063073],
       [-0.63782742],
       [-0.59969629],
       [-0.75222079],
       [-0.75222079],
       [-0.73315523],
       [-0.73315523],
       [-0.73315523],
       [-0.6950241 ],
       [-0.67595854],
       [-0.61876185],
       [-0.67595854],
       [-0.67595854],
       [-0.6950241 ],
       [-0.67595854],
       [-0.73315523],
       [-0.73315523],
       [-0.71408967],
       [-0.65689298],
       [-0.65689298],
       [-0.6950241 ],
       [-0.77128636],
       [-0.75222079],
       [-0.75222079],
       [-0.63782742],
       [-0.73315523],
       [-0.73315523],
       [-0.67595854],
       [-0.63782742],
       [-0.6950241 ],
       [-0.63782742],
       [-0.65689298],
       [-0.65689298],
       [-0.67595854],
       [-0.67595854],
       [-0.6950241 ],
       [-0.59969629],
       [-0.67595854],
       [-0.58063073],
       [-0.52343404],
       [-0.58063073],
       [-0.61876185],
       [-0.6950241 ],
       [-0.63782742],
       [-0.73315523],
       [-0.56156516],
       [-0.56156516],
       [-0.46623735],
       [-0.58063073],
       [-0.46623735],
       [-0.5424996 ],
       [-0.42810622],
       [-0.46623735],
       [-0.44717179],
       [-0.35184397],
       [-0.35184397],
       [-0.42810622],
       [-0.40904066],
       [-0.52343404],
       [-0.33277841],
       [-0.29464728],
       [-0.27558172],
       [-0.35184397],
       [-0.31371285],
       [-0.37090954],
       [-0.31371285],
       [-0.40904066],
       [-0.27558172],
       [-0.59969629],
       [-0.48530291],
       [-0.37090954],
       [-0.31371285],
       [-0.27558172],
       [-0.19931947],
       [-0.14212278],
       [-0.04679497],
       [-0.2374506 ],
       [-0.18025391],
       [-0.18025391],
       [-0.21838503],
       [-0.2374506 ],
       [-0.19931947],
       [-0.18025391],
       [-0.29464728],
       [-0.2374506 ],
       [-0.18025391],
       [-0.25651616],
       [-0.29464728],
       [-0.29464728],
       [-0.25651616],
       [-0.14212278],
       [-0.25651616],
       [-0.16118834],
       [-0.2374506 ],
       [-0.16118834],
       [-0.12305722],
       [ 0.06759841],
       [ 0.1247951 ],
       [-0.08492609],
       [-0.08492609],
       [-0.25651616],
       [-0.16118834],
       [-0.12305722],
       [-0.19931947],
       [-0.10399166],
       [-0.12305722],
       [-0.19931947],
       [-0.19931947],
       [-0.25651616],
       [-0.18025391],
       [-0.2374506 ],
       [-0.29464728],
       [-0.29464728],
       [-0.19931947],
       [-0.14212278],
       [-0.12305722],
       [-0.18025391],
       [-0.18025391],
       [ 0.01040172],
       [-0.16118834]])

In [7]:
model = load_model('./best_model_tanh/model.hdf5')

WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\ML\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\ML\lib\site-packages\keras\backend\tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING:tensorflow:From C:\ProgramData\Anaconda3\envs\ML\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.

In [8]:
pred = scaler_Y.inverse_transform(model.predict(X))
pred

array([[2.0304248],
       [2.0379777],
       [2.0294826],
       [1.9990906],
       [2.026311 ],
       [2.0276778],
       [2.0598142],
       [2.046449 ],
       [2.052798 ],
       [1.9682399],
       [1.9620996],
       [1.9082512],
       [1.9564599],
       [1.9387237],
       [1.9717424],
       [1.9459108],
       [1.9540014],
       [1.9376551],
       [1.9496181],
       [1.9511731],
       [2.0237978],
       [2.0290287],
       [1.9545442],
       [1.9624959],
       [1.9983873],
       [2.0721138],
       [2.196053 ],
       [2.230674 ],
       [2.260201 ],
       [2.138041 ],
       [2.037647 ],
       [2.0258968],
       [1.977353 ],
       [1.9656247],
       [1.9614961],
       [2.0447032],
       [2.0167828],
       [2.0465767],
       [2.0262072],
       [2.057954 ],
       [2.0579324],
       [2.0994232],
       [2.2251499],
       [2.1757877],
       [2.2954412],
       [2.3613524],
       [2.4906294],
       [2.2061899],
       [2.1491847],
       [2.0909495],
       [2.0884209],
       [2.088952 ],
       [2.0928075],
       [2.091267 ],
       [2.1248264],
       [2.1914833],
       [2.140079 ],
       [2.1629982],
       [2.1982765],
       [2.1919332],
       [2.2005634],
       [2.202105 ],
       [2.2151327],
       [2.2333555],
       [2.206774 ],
       [2.226971 ],
       [2.2769144],
       [2.1661177],
       [2.1482856],
       [2.1509178],
       [2.130249 ],
       [2.1364863],
       [2.1374314],
       [2.1452978],
       [2.1195898],
       [2.0761557],
       [2.0320563],
       [2.1255243],
       [2.1176689],
       [2.0581157],
       [2.093435 ],
       [2.1501477],
       [2.1074688],
       [2.0543425],
       [1.9904081],
       [1.9906834],
       [1.9644307],
       [1.8337475],
       [1.9651229],
       [1.9050456],
       [1.9078057],
       [1.8778535],
       [1.9460316],
       [1.9882133],
       [1.9325505],
       [1.9876988],
       [1.9911407],
       [1.9914103],
       [2.048802 ],
       [2.106422 ],
       [1.9800436],
       [1.913322 ],
       [2.0621405],
       [2.0541053],
       [2.0272753],
       [2.0126767],
       [2.0211103],
       [2.0002677],
       [2.1115937],
       [2.164797 ],
       [2.1868434],
       [2.1584525],
       [2.196708 ],
       [2.2016296],
       [2.422441 ],
       [2.3682418],
       [2.3974507],
       [2.319232 ],
       [2.3629103],
       [2.382909 ],
       [2.4776752],
       [2.5324922],
       [2.4845695],
       [2.4861133],
       [2.4669883],
       [2.45945  ],
       [2.462103 ],
       [2.4217865],
       [2.4338427],
       [2.4624548],
       [2.5364406],
       [2.5039103],
       [2.4315035],
       [2.4147155],
       [2.3154745],
       [2.3549592],
       [2.3348453],
       [2.4390678],
       [2.4134595],
       [2.4451246],
       [2.5597692],
       [2.5972402],
       [2.5205736],
       [2.4639263],
       [2.3773699],
       [2.3564568],
       [2.2776203],
       [2.2251198],
       [2.2176704],
       [2.2532547],
       [2.2762544],
       [2.2922556],
       [2.2854352],
       [2.2912796],
       [2.2767394],
       [2.2753441],
       [2.274098 ],
       [2.2391863],
       [2.2443132],
       [2.2374318],
       [2.2447367],
       [2.199815 ],
       [2.1985083],
       [2.1768506],
       [2.1658084],
       [2.161625 ],
       [2.1198764],
       [2.1549156],
       [2.170168 ],
       [2.1656065],
       [2.070108 ],
       [2.1016903],
       [2.0921264],
       [2.157558 ],
       [2.1431746],
       [2.1307976],
       [2.097706 ],
       [2.1016674],
       [1.9899119],
       [2.002455 ],
       [2.0161977],
       [1.9816512],
       [2.032474 ],
       [2.0444417],
       [2.0204585],
       [2.0204585],
       [2.032976 ],
       [1.993718 ],
       [1.9863279],
       [1.9185152],
       [1.9330932],
       [1.9306477],
       [1.9192251],
       [1.8847961],
       [1.8329864],
       [1.7986284],
       [1.7887875],
       [1.777787 ],
       [1.8085461],
       [1.7817688],
       [1.7830118],
       [1.7912952],
       [1.8004284],
       [1.8141055],
       [1.794707 ],
       [1.7735195],
       [1.7564332],
       [1.7844179],
       [1.8035265],
       [1.8037838],
       [1.8250989],
       [1.8429213],
       [1.8567623],
       [1.8897024],
       [1.9398924],
       [1.9407016],
       [1.9766054],
       [1.9497616],
       [1.952145 ],
       [1.9923826],
       [1.9928832],
       [1.9959431],
       [2.1021638],
       [2.1170168],
       [2.1179361],
       [2.0856404],
       [2.0752401],
       [2.0513527],
       [2.0411012],
       [2.05424  ],
       [2.098657 ],
       [2.1615698],
       [2.2171848],
       [2.2776492],
       [2.25896  ],
       [2.1324663],
       [2.1597373],
       [2.161939 ],
       [2.1268973],
       [2.1161368],
       [2.1005454],
       [2.0446317],
       [2.0105512],
       [2.048693 ],
       [2.0165799],
       [2.0202932],
       [2.0395055],
       [2.0420043],
       [2.0498803],
       [2.0275493],
       [1.9902451],
       [2.0178404],
       [1.9705149],
       [1.9589045],
       [1.930196 ],
       [1.9394252],
       [1.8889655],
       [1.8793548],
       [1.8750015],
       [1.8750288],
       [1.8737249],
       [1.8845334],
       [1.8946093],
       [1.9148834],
       [1.902909 ],
       [1.9059759],
       [1.8928752],
       [1.8970728],
       [1.8814311],
       [1.8790563],
       [1.8824924],
       [1.9046133],
       [1.9122798],
       [1.900183 ],
       [1.872524 ],
       [1.8694454],
       [1.8626173],
       [1.9027961],
       [1.9031376],
       [1.8815224],
       [1.9003096],
       [1.91169  ],
       [1.9001842],
       [1.9172505],
       [1.913242 ],
       [1.9145895],
       [1.9094201],
       [1.9073361],
       [1.8983567],
       [1.9288387],
       [1.9101433],
       [1.9398031],
       [1.9642617],
       [1.9529217],
       [1.9388304],
       [1.9058464],
       [1.9161795],
       [1.8828881],
       [1.9369527],
       [1.9450134],
       [1.9885288],
       [1.9572964],
       [1.9925417],
       [1.9702107],
       [2.0107327],
       [2.0017028],
       [2.0123754],
       [2.0427139],
       [2.0560524],
       [2.031813 ],
       [2.0311313],
       [1.9865726],
       [2.048933 ],
       [2.0723464],
       [2.0942702],
       [2.072314 ],
       [2.08073  ],
       [2.0583684],
       [2.0774043],
       [2.04173  ],
       [2.0867584],
       [1.9747771],
       [1.9928588],
       [2.0226572],
       [2.0633724],
       [2.0918572],
       [2.1275556],
       [2.1585302],
       [2.2019875],
       [2.1433556],
       [2.150659 ],
       [2.1451695],
       [2.1315107],
       [2.124712 ],
       [2.1303654],
       [2.142218 ],
       [2.102091 ],
       [2.1115258],
       [2.1311762],
       [2.1136065],
       [2.1140022],
       [2.098834 ],
       [2.0988476],
       [2.1434562],
       [2.1135392],
       [2.149786 ],
       [2.1268516],
       [2.154674 ],
       [2.1711285],
       [2.2559068],
       [2.2983923],
       [2.2399042],
       [2.2185888],
       [2.1353776],
       [2.15575  ],
       [2.1680727],
       [2.146538 ],
       [2.1781812],
       [2.1729631],
       [2.1523082],
       [2.1419544],
       [2.1162527],
       [2.141384 ],
       [2.1247458],
       [2.0992692],
       [2.0892975],
       [2.12485  ],
       [2.1563852],
       [2.17401  ],
       [2.1610115],
       [2.156424 ],
       [2.2305713]], dtype=float32)

In [9]:
pred.flatten()

array([2.0304248, 2.0379777, 2.0294826, 1.9990906, 2.026311 , 2.0276778,
       2.0598142, 2.046449 , 2.052798 , 1.9682399, 1.9620996, 1.9082512,
       1.9564599, 1.9387237, 1.9717424, 1.9459108, 1.9540014, 1.9376551,
       1.9496181, 1.9511731, 2.0237978, 2.0290287, 1.9545442, 1.9624959,
       1.9983873, 2.0721138, 2.196053 , 2.230674 , 2.260201 , 2.138041 ,
       2.037647 , 2.0258968, 1.977353 , 1.9656247, 1.9614961, 2.0447032,
       2.0167828, 2.0465767, 2.0262072, 2.057954 , 2.0579324, 2.0994232,
       2.2251499, 2.1757877, 2.2954412, 2.3613524, 2.4906294, 2.2061899,
       2.1491847, 2.0909495, 2.0884209, 2.088952 , 2.0928075, 2.091267 ,
       2.1248264, 2.1914833, 2.140079 , 2.1629982, 2.1982765, 2.1919332,
       2.2005634, 2.202105 , 2.2151327, 2.2333555, 2.206774 , 2.226971 ,
       2.2769144, 2.1661177, 2.1482856, 2.1509178, 2.130249 , 2.1364863,
       2.1374314, 2.1452978, 2.1195898, 2.0761557, 2.0320563, 2.1255243,
       2.1176689, 2.0581157, 2.093435 , 2.1501477, 2.1074688, 2.0543425,
       1.9904081, 1.9906834, 1.9644307, 1.8337475, 1.9651229, 1.9050456,
       1.9078057, 1.8778535, 1.9460316, 1.9882133, 1.9325505, 1.9876988,
       1.9911407, 1.9914103, 2.048802 , 2.106422 , 1.9800436, 1.913322 ,
       2.0621405, 2.0541053, 2.0272753, 2.0126767, 2.0211103, 2.0002677,
       2.1115937, 2.164797 , 2.1868434, 2.1584525, 2.196708 , 2.2016296,
       2.422441 , 2.3682418, 2.3974507, 2.319232 , 2.3629103, 2.382909 ,
       2.4776752, 2.5324922, 2.4845695, 2.4861133, 2.4669883, 2.45945  ,
       2.462103 , 2.4217865, 2.4338427, 2.4624548, 2.5364406, 2.5039103,
       2.4315035, 2.4147155, 2.3154745, 2.3549592, 2.3348453, 2.4390678,
       2.4134595, 2.4451246, 2.5597692, 2.5972402, 2.5205736, 2.4639263,
       2.3773699, 2.3564568, 2.2776203, 2.2251198, 2.2176704, 2.2532547,
       2.2762544, 2.2922556, 2.2854352, 2.2912796, 2.2767394, 2.2753441,
       2.274098 , 2.2391863, 2.2443132, 2.2374318, 2.2447367, 2.199815 ,
       2.1985083, 2.1768506, 2.1658084, 2.161625 , 2.1198764, 2.1549156,
       2.170168 , 2.1656065, 2.070108 , 2.1016903, 2.0921264, 2.157558 ,
       2.1431746, 2.1307976, 2.097706 , 2.1016674, 1.9899119, 2.002455 ,
       2.0161977, 1.9816512, 2.032474 , 2.0444417, 2.0204585, 2.0204585,
       2.032976 , 1.993718 , 1.9863279, 1.9185152, 1.9330932, 1.9306477,
       1.9192251, 1.8847961, 1.8329864, 1.7986284, 1.7887875, 1.777787 ,
       1.8085461, 1.7817688, 1.7830118, 1.7912952, 1.8004284, 1.8141055,
       1.794707 , 1.7735195, 1.7564332, 1.7844179, 1.8035265, 1.8037838,
       1.8250989, 1.8429213, 1.8567623, 1.8897024, 1.9398924, 1.9407016,
       1.9766054, 1.9497616, 1.952145 , 1.9923826, 1.9928832, 1.9959431,
       2.1021638, 2.1170168, 2.1179361, 2.0856404, 2.0752401, 2.0513527,
       2.0411012, 2.05424  , 2.098657 , 2.1615698, 2.2171848, 2.2776492,
       2.25896  , 2.1324663, 2.1597373, 2.161939 , 2.1268973, 2.1161368,
       2.1005454, 2.0446317, 2.0105512, 2.048693 , 2.0165799, 2.0202932,
       2.0395055, 2.0420043, 2.0498803, 2.0275493, 1.9902451, 2.0178404,
       1.9705149, 1.9589045, 1.930196 , 1.9394252, 1.8889655, 1.8793548,
       1.8750015, 1.8750288, 1.8737249, 1.8845334, 1.8946093, 1.9148834,
       1.902909 , 1.9059759, 1.8928752, 1.8970728, 1.8814311, 1.8790563,
       1.8824924, 1.9046133, 1.9122798, 1.900183 , 1.872524 , 1.8694454,
       1.8626173, 1.9027961, 1.9031376, 1.8815224, 1.9003096, 1.91169  ,
       1.9001842, 1.9172505, 1.913242 , 1.9145895, 1.9094201, 1.9073361,
       1.8983567, 1.9288387, 1.9101433, 1.9398031, 1.9642617, 1.9529217,
       1.9388304, 1.9058464, 1.9161795, 1.8828881, 1.9369527, 1.9450134,
       1.9885288, 1.9572964, 1.9925417, 1.9702107, 2.0107327, 2.0017028,
       2.0123754, 2.0427139, 2.0560524, 2.031813 , 2.0311313, 1.9865726,
       2.048933 , 2.0723464, 2.0942702, 2.072314 , 2.08073  , 2.0583684,
       2.0774043, 2.04173  , 2.0867584, 1.9747771, 1.9928588, 2.0226572,
       2.0633724, 2.0918572, 2.1275556, 2.1585302, 2.2019875, 2.1433556,
       2.150659 , 2.1451695, 2.1315107, 2.124712 , 2.1303654, 2.142218 ,
       2.102091 , 2.1115258, 2.1311762, 2.1136065, 2.1140022, 2.098834 ,
       2.0988476, 2.1434562, 2.1135392, 2.149786 , 2.1268516, 2.154674 ,
       2.1711285, 2.2559068, 2.2983923, 2.2399042, 2.2185888, 2.1353776,
       2.15575  , 2.1680727, 2.146538 , 2.1781812, 2.1729631, 2.1523082,
       2.1419544, 2.1162527, 2.141384 , 2.1247458, 2.0992692, 2.0892975,
       2.12485  , 2.1563852, 2.17401  , 2.1610115, 2.156424 , 2.2305713],
      dtype=float32)

In [28]:
startDate = "2018-01-01"
endDate = "2018-12-31"
datelist = pd.date_range(startDate,endDate)
date_list=[x.strftime('%Y-%m-%d') for x in datelist]
date_list

['2018-01-01',
 '2018-01-02',
 '2018-01-03',
 '2018-01-04',
 '2018-01-05',
 '2018-01-06',
 '2018-01-07',
 '2018-01-08',
 '2018-01-09',
 '2018-01-10',
 '2018-01-11',
 '2018-01-12',
 '2018-01-13',
 '2018-01-14',
 '2018-01-15',
 '2018-01-16',
 '2018-01-17',
 '2018-01-18',
 '2018-01-19',
 '2018-01-20',
 '2018-01-21',
 '2018-01-22',
 '2018-01-23',
 '2018-01-24',
 '2018-01-25',
 '2018-01-26',
 '2018-01-27',
 '2018-01-28',
 '2018-01-29',
 '2018-01-30',
 '2018-01-31',
 '2018-02-01',
 '2018-02-02',
 '2018-02-03',
 '2018-02-04',
 '2018-02-05',
 '2018-02-06',
 '2018-02-07',
 '2018-02-08',
 '2018-02-09',
 '2018-02-10',
 '2018-02-11',
 '2018-02-12',
 '2018-02-13',
 '2018-02-14',
 '2018-02-15',
 '2018-02-16',
 '2018-02-17',
 '2018-02-18',
 '2018-02-19',
 '2018-02-20',
 '2018-02-21',
 '2018-02-22',
 '2018-02-23',
 '2018-02-24',
 '2018-02-25',
 '2018-02-26',
 '2018-02-27',
 '2018-02-28',
 '2018-03-01',
 '2018-03-02',
 '2018-03-03',
 '2018-03-04',
 '2018-03-05',
 '2018-03-06',
 '2018-03-07',
 '2018-03-08',
 '2018-03-09',
 '2018-03-10',
 '2018-03-11',
 '2018-03-12',
 '2018-03-13',
 '2018-03-14',
 '2018-03-15',
 '2018-03-16',
 '2018-03-17',
 '2018-03-18',
 '2018-03-19',
 '2018-03-20',
 '2018-03-21',
 '2018-03-22',
 '2018-03-23',
 '2018-03-24',
 '2018-03-25',
 '2018-03-26',
 '2018-03-27',
 '2018-03-28',
 '2018-03-29',
 '2018-03-30',
 '2018-03-31',
 '2018-04-01',
 '2018-04-02',
 '2018-04-03',
 '2018-04-04',
 '2018-04-05',
 '2018-04-06',
 '2018-04-07',
 '2018-04-08',
 '2018-04-09',
 '2018-04-10',
 '2018-04-11',
 '2018-04-12',
 '2018-04-13',
 '2018-04-14',
 '2018-04-15',
 '2018-04-16',
 '2018-04-17',
 '2018-04-18',
 '2018-04-19',
 '2018-04-20',
 '2018-04-21',
 '2018-04-22',
 '2018-04-23',
 '2018-04-24',
 '2018-04-25',
 '2018-04-26',
 '2018-04-27',
 '2018-04-28',
 '2018-04-29',
 '2018-04-30',
 '2018-05-01',
 '2018-05-02',
 '2018-05-03',
 '2018-05-04',
 '2018-05-05',
 '2018-05-06',
 '2018-05-07',
 '2018-05-08',
 '2018-05-09',
 '2018-05-10',
 '2018-05-11',
 '2018-05-12',
 '2018-05-13',
 '2018-05-14',
 '2018-05-15',
 '2018-05-16',
 '2018-05-17',
 '2018-05-18',
 '2018-05-19',
 '2018-05-20',
 '2018-05-21',
 '2018-05-22',
 '2018-05-23',
 '2018-05-24',
 '2018-05-25',
 '2018-05-26',
 '2018-05-27',
 '2018-05-28',
 '2018-05-29',
 '2018-05-30',
 '2018-05-31',
 '2018-06-01',
 '2018-06-02',
 '2018-06-03',
 '2018-06-04',
 '2018-06-05',
 '2018-06-06',
 '2018-06-07',
 '2018-06-08',
 '2018-06-09',
 '2018-06-10',
 '2018-06-11',
 '2018-06-12',
 '2018-06-13',
 '2018-06-14',
 '2018-06-15',
 '2018-06-16',
 '2018-06-17',
 '2018-06-18',
 '2018-06-19',
 '2018-06-20',
 '2018-06-21',
 '2018-06-22',
 '2018-06-23',
 '2018-06-24',
 '2018-06-25',
 '2018-06-26',
 '2018-06-27',
 '2018-06-28',
 '2018-06-29',
 '2018-06-30',
 '2018-07-01',
 '2018-07-02',
 '2018-07-03',
 '2018-07-04',
 '2018-07-05',
 '2018-07-06',
 '2018-07-07',
 '2018-07-08',
 '2018-07-09',
 '2018-07-10',
 '2018-07-11',
 '2018-07-12',
 '2018-07-13',
 '2018-07-14',
 '2018-07-15',
 '2018-07-16',
 '2018-07-17',
 '2018-07-18',
 '2018-07-19',
 '2018-07-20',
 '2018-07-21',
 '2018-07-22',
 '2018-07-23',
 '2018-07-24',
 '2018-07-25',
 '2018-07-26',
 '2018-07-27',
 '2018-07-28',
 '2018-07-29',
 '2018-07-30',
 '2018-07-31',
 '2018-08-01',
 '2018-08-02',
 '2018-08-03',
 '2018-08-04',
 '2018-08-05',
 '2018-08-06',
 '2018-08-07',
 '2018-08-08',
 '2018-08-09',
 '2018-08-10',
 '2018-08-11',
 '2018-08-12',
 '2018-08-13',
 '2018-08-14',
 '2018-08-15',
 '2018-08-16',
 '2018-08-17',
 '2018-08-18',
 '2018-08-19',
 '2018-08-20',
 '2018-08-21',
 '2018-08-22',
 '2018-08-23',
 '2018-08-24',
 '2018-08-25',
 '2018-08-26',
 '2018-08-27',
 '2018-08-28',
 '2018-08-29',
 '2018-08-30',
 '2018-08-31',
 '2018-09-01',
 '2018-09-02',
 '2018-09-03',
 '2018-09-04',
 '2018-09-05',
 '2018-09-06',
 '2018-09-07',
 '2018-09-08',
 '2018-09-09',
 '2018-09-10',
 '2018-09-11',
 '2018-09-12',
 '2018-09-13',
 '2018-09-14',
 '2018-09-15',
 '2018-09-16',
 '2018-09-17',
 '2018-09-18',
 '2018-09-19',
 '2018-09-20',
 '2018-09-21',
 '2018-09-22',
 '2018-09-23',
 '2018-09-24',
 '2018-09-25',
 '2018-09-26',
 '2018-09-27',
 '2018-09-28',
 '2018-09-29',
 '2018-09-30',
 '2018-10-01',
 '2018-10-02',
 '2018-10-03',
 '2018-10-04',
 '2018-10-05',
 '2018-10-06',
 '2018-10-07',
 '2018-10-08',
 '2018-10-09',
 '2018-10-10',
 '2018-10-11',
 '2018-10-12',
 '2018-10-13',
 '2018-10-14',
 '2018-10-15',
 '2018-10-16',
 '2018-10-17',
 '2018-10-18',
 '2018-10-19',
 '2018-10-20',
 '2018-10-21',
 '2018-10-22',
 '2018-10-23',
 '2018-10-24',
 '2018-10-25',
 '2018-10-26',
 '2018-10-27',
 '2018-10-28',
 '2018-10-29',
 '2018-10-30',
 '2018-10-31',
 '2018-11-01',
 '2018-11-02',
 '2018-11-03',
 '2018-11-04',
 '2018-11-05',
 '2018-11-06',
 '2018-11-07',
 '2018-11-08',
 '2018-11-09',
 '2018-11-10',
 '2018-11-11',
 '2018-11-12',
 '2018-11-13',
 '2018-11-14',
 '2018-11-15',
 '2018-11-16',
 '2018-11-17',
 '2018-11-18',
 '2018-11-19',
 '2018-11-20',
 '2018-11-21',
 '2018-11-22',
 '2018-11-23',
 '2018-11-24',
 '2018-11-25',
 '2018-11-26',
 '2018-11-27',
 '2018-11-28',
 '2018-11-29',
 '2018-11-30',
 '2018-12-01',
 '2018-12-02',
 '2018-12-03',
 '2018-12-04',
 '2018-12-05',
 '2018-12-06',
 '2018-12-07',
 '2018-12-08',
 '2018-12-09',
 '2018-12-10',
 '2018-12-11',
 '2018-12-12',
 '2018-12-13',
 '2018-12-14',
 '2018-12-15',
 '2018-12-16',
 '2018-12-17',
 '2018-12-18',
 '2018-12-19',
 '2018-12-20',
 '2018-12-21',
 '2018-12-22',
 '2018-12-23',
 '2018-12-24',
 '2018-12-25',
 '2018-12-26',
 '2018-12-27',
 '2018-12-28',
 '2018-12-29',
 '2018-12-30',
 '2018-12-31']